# 1. Title and Introduction

## Equal Grades, Unequal Pay: Examining Internal Pay Disparities in the DC Government Workforce
### The data set is from Open Data DC, a DC government Data source under the Enterprise Data team in the Office of the Chief Technology Officer (OCTO). The specific Data Set This data set is the DC Public Employee Salary which was published September 15, 2023 which was updated quarterly up until September 26, 2024. Then it shifted to as needed status. This dataset represents employee names, position title, agency, appointment type, salary grade, and hire date. Its analytically compelling because as myself and my peers look into the job market the most important factor to consider is salary so by looking at factors that may impact salary such as grade, agency, and hiring date.

# 2. Objective and Research Question(s)

#### By comparing agency, hiring date, and salary grade I hope to identify pay disparities across the larger DC Public Sector. 
### My Research Questions were as follows: 
####  What is the correlation between hiring year and grade?
#### Do employees with different appointments earn systemically different rates in the same grade?

# 3. Data Understanding and Cleaning

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.ensemble import IsolationForest

In [4]:
df = pd.read_csv('DC_Public_Employee_Salary.csv')
df

,FIRST_NAME,LAST_NAME,JOBTITLE,DESCRSHORT,GRADE,COMPRATE,HIREDATE_STRING,GVT_TYPE_OF_APPT,OBJECTID
0,Natasha,Boley,Compliance Specialist,DBH,13,123873.00,2004/10/18,CS - Reg,1
1,Korlu,Wolobah-Kuyon,PSYCHIATRIC NURSE,DBH,09,115907.00,2020/08/17,CS - Reg,2
2,Hadizat,Elayo-Ross,SUPERVISORY PSYCHIATRIC NURSE,DBH,13,122500.00,2023/08/14,MSS - Reg,3
3,Gary,Evans,Climate Control Maint Mechanic,DBH,11,41.73,1985/08/27,CS - Reg,4
4,Jemia,Gross,Special Police Officer,DBH,08,75787.00,2016/11/14,CS - Reg,5
...,...,...,...,...,...,...,...,...,...
40606,Zaid,Coleman,ADJUNCT INSTRUCTOR - WDLL,UDC,01,0.03,2023/01/03,Ed - Temp,40607
40607,Pablo,Larreategui Plaza,Adjunct Professor-SEIU,UDC,01,210.00,2025/05/16,Ed - Temp,40608
40608,Myron,Douglas,ASST PROFESSOR,UDC,04,83843.46,2008/06/01,Ed - Reg,40609
40609,Yoko,Ferguson,ASSOCIATE PROFESSOR,UDC,03,91965.50,2022/08/16,Ed - Reg,40610
40610,Spiros,Giannaros,ASST PROFESSOR,UDC,04,82465.00,2023/08/16,Ed - Reg,40611

### Head, Tail, shape, data types

In [5]:
df.head(5)

,FIRST_NAME,LAST_NAME,JOBTITLE,DESCRSHORT,GRADE,COMPRATE,HIREDATE_STRING,GVT_TYPE_OF_APPT,OBJECTID
0,Natasha,Boley,Compliance Specialist,DBH,13,123873.00,2004/10/18,CS - Reg,1
1,Korlu,Wolobah-Kuyon,PSYCHIATRIC NURSE,DBH,09,115907.00,2020/08/17,CS - Reg,2
2,Hadizat,Elayo-Ross,SUPERVISORY PSYCHIATRIC NURSE,DBH,13,122500.00,2023/08/14,MSS - Reg,3
3,Gary,Evans,Climate Control Maint Mechanic,DBH,11,41.73,1985/08/27,CS - Reg,4
4,Jemia,Gross,Special Police Officer,DBH,08,75787.00,2016/11/14,CS - Reg,5

In [6]:
df.tail(5)

,FIRST_NAME,LAST_NAME,JOBTITLE,DESCRSHORT,GRADE,COMPRATE,HIREDATE_STRING,GVT_TYPE_OF_APPT,OBJECTID
40606,Zaid,Coleman,ADJUNCT INSTRUCTOR - WDLL,UDC,01,0.03,2023/01/03,Ed - Temp,40607
40607,Pablo,Larreategui Plaza,Adjunct Professor-SEIU,UDC,01,210.00,2025/05/16,Ed - Temp,40608
40608,Myron,Douglas,ASST PROFESSOR,UDC,04,83843.46,2008/06/01,Ed - Reg,40609
40609,Yoko,Ferguson,ASSOCIATE PROFESSOR,UDC,03,91965.50,2022/08/16,Ed - Reg,40610
40610,Spiros,Giannaros,ASST PROFESSOR,UDC,04,82465.00,2023/08/16,Ed - Reg,40611

In [7]:
df.shape

(40611, 9)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40611 entries, 0 to 40610
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   FIRST_NAME        40611 non-null  object
 1   LAST_NAME         40611 non-null  object
 2   JOBTITLE          40611 non-null  object
 3   DESCRSHORT        40611 non-null  object
 4   GRADE             40571 non-null  object
 5   COMPRATE          40611 non-null  float64
 6   HIREDATE_STRING   40611 non-null  object
 7   GVT_TYPE_OF_APPT  40611 non-null  object
 8   OBJECTID          40611 non-null  int64
dtypes: float64(1), int64(1), object(7)
memory usage: 2.8+ MB

### Summary Statistics

In [9]:
df.describe()

            COMPRATE      OBJECTID
count   40611.000000  40611.000000
mean    89087.755572  20306.000000
std     47453.788915  11723.530228
min         0.030000      1.000000
25%     66130.000000  10153.500000
50%     93234.000000  20306.000000
75%    119643.130000  30458.500000
max    390232.000000  40611.000000

#### The summary statistics of the COMPRATE column reveal that the average DC employee in this Data set makes around $89,087. Which based on the ABC7 analysis is about $12,000 under what DC single residents need to live comfortably.

### Detecting and resolving missing or invalid values

In [10]:
df.isnull().sum()

FIRST_NAME           0
LAST_NAME            0
JOBTITLE             0
DESCRSHORT           0
GRADE               40
COMPRATE             0
HIREDATE_STRING      0
GVT_TYPE_OF_APPT     0
OBJECTID             0
dtype: int64

In [11]:
df_temp = df.dropna().copy()
df_temp

,FIRST_NAME,LAST_NAME,JOBTITLE,DESCRSHORT,GRADE,COMPRATE,HIREDATE_STRING,GVT_TYPE_OF_APPT,OBJECTID
0,Natasha,Boley,Compliance Specialist,DBH,13,123873.00,2004/10/18,CS - Reg,1
1,Korlu,Wolobah-Kuyon,PSYCHIATRIC NURSE,DBH,09,115907.00,2020/08/17,CS - Reg,2
2,Hadizat,Elayo-Ross,SUPERVISORY PSYCHIATRIC NURSE,DBH,13,122500.00,2023/08/14,MSS - Reg,3
3,Gary,Evans,Climate Control Maint Mechanic,DBH,11,41.73,1985/08/27,CS - Reg,4
4,Jemia,Gross,Special Police Officer,DBH,08,75787.00,2016/11/14,CS - Reg,5
...,...,...,...,...,...,...,...,...,...
40606,Zaid,Coleman,ADJUNCT INSTRUCTOR - WDLL,UDC,01,0.03,2023/01/03,Ed - Temp,40607
40607,Pablo,Larreategui Plaza,Adjunct Professor-SEIU,UDC,01,210.00,2025/05/16,Ed - Temp,40608
40608,Myron,Douglas,ASST PROFESSOR,UDC,04,83843.46,2008/06/01,Ed - Reg,40609
40609,Yoko,Ferguson,ASSOCIATE PROFESSOR,UDC,03,91965.50,2022/08/16,Ed - Reg,40610
40610,Spiros,Giannaros,ASST PROFESSOR,UDC,04,82465.00,2023/08/16,Ed - Reg,40611

### Removing Duplicate records

In [12]:
df_temp.duplicated().sum()

np.int64(0)

### Stardardizing Column names

In [13]:
df_temp.rename(columns={'GVT_TYPE_OF_APPT':'APPT_TYPE'}, inplace=True)

,FIRST_NAME,LAST_NAME,JOBTITLE,DESCRSHORT,GRADE,COMPRATE,HIREDATE_STRING,APPT_TYPE,OBJECTID
0,Natasha,Boley,Compliance Specialist,DBH,13,123873.00,2004/10/18,CS - Reg,1
1,Korlu,Wolobah-Kuyon,PSYCHIATRIC NURSE,DBH,09,115907.00,2020/08/17,CS - Reg,2
2,Hadizat,Elayo-Ross,SUPERVISORY PSYCHIATRIC NURSE,DBH,13,122500.00,2023/08/14,MSS - Reg,3
3,Gary,Evans,Climate Control Maint Mechanic,DBH,11,41.73,1985/08/27,CS - Reg,4
4,Jemia,Gross,Special Police Officer,DBH,08,75787.00,2016/11/14,CS - Reg,5
...,...,...,...,...,...,...,...,...,...
40606,Zaid,Coleman,ADJUNCT INSTRUCTOR - WDLL,UDC,01,0.03,2023/01/03,Ed - Temp,40607
40607,Pablo,Larreategui Plaza,Adjunct Professor-SEIU,UDC,01,210.00,2025/05/16,Ed - Temp,40608
40608,Myron,Douglas,ASST PROFESSOR,UDC,04,83843.46,2008/06/01,Ed - Reg,40609
40609,Yoko,Ferguson,ASSOCIATE PROFESSOR,UDC,03,91965.50,2022/08/16,Ed - Reg,40610
40610,Spiros,Giannaros,ASST PROFESSOR,UDC,04,82465.00,2023/08/16,Ed - Reg,40611

In [15]:
df_temp['JOBTITLE'] = df_temp['JOBTITLE'].str.strip()
df_temp['JOBTITLE'] = df_temp['JOBTITLE'].str.title()

### Encoding or converting cateorical variabes

In [16]:
df_temp['GRADE_NUM'] = df_temp['GRADE'].astype(str).str.replace(r'\D+', '', regex=True)
df_temp['GRADE_NUM'] = pd.to_numeric(df_temp['GRADE_NUM'], errors='coerce').astype('Int64')

### Parsing date strings to date time objects

In [17]:
df_temp['HIREDATE'] = pd.to_datetime(df_temp['HIREDATE_STRING'], errors='coerce')
print(df_temp['HIREDATE'].dtype)

datetime64[ns]

In [18]:
df_temp['YEAR'] = df_temp['HIREDATE'].dt.year

In [19]:
df_temp['YEAR'] = df_temp['YEAR'].astype('Int64')

## Dropping irrelevant and redundant columns

In [20]:
df_temp2 = df_temp.drop(columns=['GRADE']).copy()
df_temp2

,FIRST_NAME,LAST_NAME,JOBTITLE,DESCRSHORT,COMPRATE,HIREDATE_STRING,APPT_TYPE,OBJECTID,GRADE_NUM,HIREDATE,YEAR
0,Natasha,Boley,Compliance Specialist,DBH,123873.00,2004/10/18,CS - Reg,1,13,2004-10-18,2004
1,Korlu,Wolobah-Kuyon,Psychiatric Nurse,DBH,115907.00,2020/08/17,CS - Reg,2,9,2020-08-17,2020
2,Hadizat,Elayo-Ross,Supervisory Psychiatric Nurse,DBH,122500.00,2023/08/14,MSS - Reg,3,13,2023-08-14,2023
3,Gary,Evans,Climate Control Maint Mechanic,DBH,41.73,1985/08/27,CS - Reg,4,11,1985-08-27,1985
4,Jemia,Gross,Special Police Officer,DBH,75787.00,2016/11/14,CS - Reg,5,8,2016-11-14,2016
...,...,...,...,...,...,...,...,...,...,...,...
40606,Zaid,Coleman,Adjunct Instructor - Wdll,UDC,0.03,2023/01/03,Ed - Temp,40607,1,2023-01-03,2023
40607,Pablo,Larreategui Plaza,Adjunct Professor-Seiu,UDC,210.00,2025/05/16,Ed - Temp,40608,1,2025-05-16,2025
40608,Myron,Douglas,Asst Professor,UDC,83843.46,2008/06/01,Ed - Reg,40609,4,2008-06-01,2008
40609,Yoko,Ferguson,Associate Professor,UDC,91965.50,2022/08/16,Ed - Reg,40610,3,2022-08-16,2022
40610,Spiros,Giannaros,Asst Professor,UDC,82465.00,2023/08/16,Ed - Reg,40611,4,2023-08-16,2023

In [0]:
# OBJECTID already excluded when df_temp2 was created above (drop GRADE, keep rest)
# No additional drop needed here

### Standardizing columns to make it easier to create readable visualizations

In [21]:
main_types = ['CS - Reg', 'CS - Temp', 'MSS - Reg', 'MSS - Temp']
df_temp3 = df_temp2[df_temp2['APPT_TYPE'].isin(main_types)].copy()

In [22]:
top_grades = df_temp3['GRADE_NUM'].value_counts().nlargest(10).index
df_temp4 = df_temp3[df_temp3['GRADE_NUM'].isin(top_grades)]

In [23]:
df_filtered = df_temp4.copy()

In [24]:
df_filtered

,FIRST_NAME,LAST_NAME,JOBTITLE,DESCRSHORT,COMPRATE,HIREDATE_STRING,APPT_TYPE,OBJECTID,GRADE_NUM,HIREDATE,YEAR
0,Natasha,Boley,Compliance Specialist,DBH,123873.00,2004/10/18,CS - Reg,1,13,2004-10-18,2004
1,Korlu,Wolobah-Kuyon,Psychiatric Nurse,DBH,115907.00,2020/08/17,CS - Reg,2,9,2020-08-17,2020
2,Hadizat,Elayo-Ross,Supervisory Psychiatric Nurse,DBH,122500.00,2023/08/14,MSS - Reg,3,13,2023-08-14,2023
3,Gary,Evans,Climate Control Maint Mechanic,DBH,41.73,1985/08/27,CS - Reg,4,11,1985-08-27,1985
4,Jemia,Gross,Special Police Officer,DBH,75787.00,2016/11/14,CS - Reg,5,8,2016-11-14,2016
...,...,...,...,...,...,...,...,...,...,...,...
40566,Christopher,Lundt,Economist,PSC,117029.00,2021/04/26,CS - Reg,40567,13,2021-04-26,2021
40567,Lynn,Williams,Telecomm Equipment Operator,OUC,72845.00,2011/07/18,CS - Reg,40568,8,2011-07-18,2011
40569,Aminta,Daves,Special Assistant,PSC,103333.00,2006/01/09,CS - Reg,40570,12,2006-01-09,2006
40577,Marie,Nkumbe,Financial Systems Manager,UDC,130720.00,2010/08/16,CS - Reg,40578,13,2010-08-16,2010
40604,Pablo,Larreategui Plaza,Adjunct Professor-Seiu,UDC,105.00,2025/10/16,CS - Reg,40605,1,2025-10-16,2025

# Exploratory Data Analysis

### Summary statistics

In [25]:
df_filtered.describe()

,COMPRATE,OBJECTID,GRADE_NUM,HIREDATE,YEAR
count,20098.000000,20098.000000,20098.0,20098,20098.0
mean,96554.451043,22795.887402,8.892825,2012-12-21 02:15:46.482236928,2012.45706
min,18.000000,1.000000,1.0,1966-07-30 00:00:00,1966.0
25%,74893.000000,17465.250000,7.0,2006-09-05 00:00:00,2006.0
50%,98322.000000,24337.500000,11.0,2015-03-23 00:00:00,2015.0
75%,118558.000000,30643.750000,12.0,2021-01-19 00:00:00,2021.0
max,255000.000000,40605.000000,15.0,2025-12-29 00:00:00,2025.0
std,34708.122679,10583.354522,4.554629,NaN,9.834151

## Frequency and value counts

In [26]:
cat_cols = df_filtered.select_dtypes(include=['object', 'category']).columns

for col in cat_cols:
    if col in df_filtered.columns:  
        print(f"--- Frequency Counts for {col} ---")
        print(df_filtered[col].value_counts())
        print("\n")

--- Frequency Counts for FIRST_NAME ---
FIRST_NAME
Michael        291
Robert         172
Christopher    171
James          170
David          153
              ...
Tazwell          1
Kamaal           1
Rex              1
La'Shan          1
Adama            1
Name: count, Length: 7015, dtype: int64


--- Frequency Counts for LAST_NAME ---
LAST_NAME
Williams    314
Johnson     281
Smith       213
Brown       213
Jones       197
           ...
Brault        1
Horta         1
Tulenko       1
Borner        1
Ravlin        1
Name: count, Length: 8561, dtype: int64


--- Frequency Counts for JOBTITLE ---
JOBTITLE
Officer                           1747
Firefighter Emt                    971
Program Analyst                    543
Correctional Officer               534
Sergeant                           469
                                  ...
Program Advisor                      1
Deputy Director For Victim Ser       1
Call Center Operations Mgr           1
Regulatory Docket Specialist         1
Sergeant, School Police              1
Name: count, Length: 2554, dtype: int64


--- Frequency Counts for DESCRSHORT ---
DESCRSHORT
MPD     3318
FEMS    2051
OCFO    1263
DHS     1055
DBH     1019
        ...
PERB       3
RHC        2
JNC        1
GN0        1
SCDC       1
Name: count, Length: 83, dtype: int64


--- Frequency Counts for HIREDATE_STRING ---
HIREDATE_STRING
2025/10/20    118
2017/02/01    115
2024/01/16    107
2022/12/05     94
2023/12/18     92
             ...
1988/02/21      1
2000/12/11      1
1997/06/25      1
2022/01/16      1
1993/03/21      1
Name: count, Length: 2805, dtype: int64


--- Frequency Counts for APPT_TYPE ---
APPT_TYPE
CS - Reg      17406
MSS - Reg      2311
CS - Temp       348
MSS - Temp       33
Name: count, dtype: int64

### Temporal Trends and Seasonality detection

In [27]:
monthly_avg = df_filtered.groupby(df_filtered['HIREDATE'].dt.to_period('M'))['COMPRATE'].mean()
print(monthly_avg.head(10))

df_filtered['COMPRATE_ROLLING'] = df_filtered['COMPRATE'].rolling(window=7).mean()

HIREDATE
1966-07    127621.64
1966-09        42.62
1968-11     96547.00
1969-04     96547.00
1969-06     58880.00
1969-09        42.62
1970-03        47.93
1971-06    100827.00
1972-07        38.51
1972-10     72721.00
Freq: M, Name: COMPRATE, dtype: float64

### Group Level Comparisons and Aggregations

In [28]:
summary = df_filtered.groupby('DESCRSHORT').agg({
    'GRADE_NUM': 'mean',
    'COMPRATE': ['sum', 'std', 'count']
})
print(summary)

            GRADE_NUM     COMPRATE
                 mean          sum           std count
DESCRSHORT
ABCA        11.553846   6641463.74  27963.044120    65
ANC         12.142857    635924.00  30382.781323     7
BEGA        11.454545    969062.75  36577.818721    11
BOE         11.288462   4971583.97  35560.472406    52
CAB              11.0    369929.19  45511.409982     4
...               ...          ...           ...   ...
PSC         13.409639  10685789.62  28025.815220    83
RHC              10.5    187584.00  42540.958170     2
RPTAC            12.0    238795.13  45205.786875     5
SCDC              7.0    105000.00           NaN     1
UDC          8.130435   4354810.89  50069.826933    69

[83 rows x 4 columns]

In [29]:
print("Average Salary by Department:")
print(df.groupby('DESCRSHORT')['COMPRATE'].mean())

Average Salary by Department:
DESCRSHORT
ABCA     105938.629571
ANC      107897.100000
BEGA     117412.284348
BOE       93199.549000
CAB      146127.447273
             ...
RHC      138841.731429
RPTAC     84447.029333
SCDC     108923.298750
SI        70540.500000
UDC       44201.097448
Name: COMPRATE, Length: 88, dtype: float64

### Outlier detection and anomalous pattern identification

In [30]:
iso_forest = IsolationForest(contamination=0.05)
iso_forest.fit(df_filtered[['GRADE_NUM', 'COMPRATE']].dropna().values)
df_filtered = df_filtered.copy()
df_filtered['Anomaly_Score'] = iso_forest.predict(
    df_filtered[['GRADE_NUM', 'COMPRATE']].fillna(df_filtered[['GRADE_NUM', 'COMPRATE']].median()).values
)